-- Compatibility migration retained after the removal flag was introduced in 0005.
-- The flag already exists in production and in fresh databases created from 0005.
-- No schema change is required here.
