const GITHUB_API = "https://api.github.com";
const REPO = "thberry84-autumn/Autumn-Nails";
const GALLERY_PATH = "images/nails";
const CAPTIONS_FILE = `${GALLERY_PATH}/captions.json`;
const SITE_ORIGINS = new Set(["https://autumnnails.com", "https://www.autumnnails.com"]);
const MAX_FILE_SIZE = 8 * 1024 * 1024;
const SESSION_MAX_AGE = 12 * 60 * 60;
export default { async fetch(request, env) { const origin=request.headers.get("Origin"); const corsOrigin=SITE_ORIGINS.has(origin)?origin:"https://autumnnails.com"; if(request.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders(corsOrigin)}); const url=new URL(request.url); try { if(url.pathname==="/health"&&request.method==="GET")return json({ok:true,service:"autumn-nails-upload"},200,corsOrigin); if(url.pathname==="/api/login"&&request.method==="POST")return await login(request,env,corsOrigin); if(url.pathname==="/api/logout"&&request.method==="POST")return json({ok:true},200,corsOrigin); if(url.pathname==="/api/session"&&request.method==="GET")return json({authenticated:Boolean(await readSession(request,env))},200,corsOrigin); if(url.pathname==="/api/gallery"&&request.method==="GET")return json({files:await listGallery(env)},200,corsOrigin,{"Cache-Control":"no-store"}); if(url.pathname==="/api/upload"&&request.method==="POST"){if(!await readSession(request,env))return json({error:"Not authorised"},401,corsOrigin);return await uploadFiles(request,env,corsOrigin)} if(url.pathname.startsWith("/api/gallery/")&&request.method==="DELETE"){if(!await readSession(request,env))return json({error:"Not authorised"},401,corsOrigin);return await deleteFile(decodeURIComponent(url.pathname.slice(13)),env,corsOrigin)} return json({error:"Not found"},404,corsOrigin) } catch(error){console.error(error);return json({error:"Something went wrong. Please try again."},500,corsOrigin)} } };
function corsHeaders(origin){return {"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Credentials":"true","Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS","Vary":"Origin","X-Content-Type-Options":"nosniff","Referrer-Policy":"strict-origin-when-cross-origin"}}
function json(data,status,origin,extra={}){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(origin),"Content-Type":"application/json; charset=utf-8",...extra}})}
async function login(request,env,origin){if(!env.ADMIN_EMAIL||!env.ADMIN_PASSWORD||!env.SESSION_SECRET)return json({error:"Admin login has not been configured yet."},503,origin);const body=await request.json();const email=String(body.email||"").trim().toLowerCase();const password=String(body.password||"");if(email!==env.ADMIN_EMAIL.trim().toLowerCase()||password!==env.ADMIN_PASSWORD)return json({error:"Incorrect email or password."},401,origin);const payload=`${email}|${Date.now()+SESSION_MAX_AGE*1000}`;const signature=await sign(payload,env.SESSION_SECRET);const token=`${b64url(payload)}.${signature}`;return json({ok:true,token},200,origin)}
async function readSession(request,env){if(!env.SESSION_SECRET)return null;const auth=request.headers.get("Authorization")||"";const token=auth.startsWith("Bearer ")?auth.slice(7).trim():null;if(!token)return null;const [encodedPayload,signature]=token.split(".");if(!encodedPayload||!signature)return null;try{const payload=fromB64url(encodedPayload);if(!safeEqual(signature,await sign(payload,env.SESSION_SECRET)))return null;const separator=payload.lastIndexOf("|");const email=payload.slice(0,separator);const expiry=Number(payload.slice(separator+1));if(!email||!Number.isFinite(expiry)||Date.now()>expiry)return null;if(env.ADMIN_EMAIL&&email!==env.ADMIN_EMAIL.trim().toLowerCase())return null;return{email,expiry}}catch{return null}}
async function uploadFiles(request,env,origin){const form=await request.formData();const files=form.getAll("files").filter(v=>v instanceof File);if(!files.length)return json({error:"No photos were selected."},400,origin);if(files.length>20)return json({error:"Please upload no more than 20 photos at once."},400,origin);let captions={};try{captions=JSON.parse(String(form.get("captions")||"{}"))}catch{return json({error:"The captions could not be read."},400,origin)}const metadata=await getCaptions(env);const uploaded=[];for(let i=0;i<files.length;i++){const file=files[i];if(!/^image\/(jpeg|png|webp)$/.test(file.type))return json({error:`${file.name} is not a supported image type.`},400,origin);if(file.size>MAX_FILE_SIZE)return json({error:`${file.name} is larger than 8 MB.`},400,origin);const filename=makeFilename(file.name);const content=await toBase64(await file.arrayBuffer());const result=await githubRequest(`/repos/${REPO}/contents/${GALLERY_PATH}/${encodeURIComponent(filename)}`,env.GITHUB_TOKEN,{method:"PUT",body:JSON.stringify({message:`Add nail photo ${filename}`,content})});if(!result.ok){console.error("GitHub upload failed",result.status,await result.text());return json({error:`GitHub could not save ${file.name}.`},502,origin)}metadata[filename]=String(captions[String(i)]||"").trim().slice(0,180);uploaded.push({name:filename,caption:metadata[filename]})}await saveCaptions(metadata,env);return json({ok:true,uploaded},200,origin,{"Cache-Control":"no-store"})}
async function listGallery(env){const result=await githubRequest(`/repos/${REPO}/contents/${GALLERY_PATH}`,env.GITHUB_TOKEN);if(!result.ok)throw new Error(`GitHub gallery request failed: ${result.status}`);const items=await result.json();const captions=await getCaptions(env);return items.filter(i=>i.type==="file"&&/\.(jpe?g|png|webp)$/i.test(i.name)).sort((a,b)=>b.name.localeCompare(a.name)).map(i=>({name:i.name,caption:captions[i.name]||"",url:`https://raw.githubusercontent.com/${REPO}/main/${GALLERY_PATH}/${encodeURIComponent(i.name)}`}))}
async function deleteFile(filename,env,origin){if(!/^[\w .()\-]+\.(jpe?g|png|webp)$/i.test(filename))return json({error:"Invalid filename."},400,origin);const path=`${GALLERY_PATH}/${encodeURIComponent(filename)}`;const current=await githubRequest(`/repos/${REPO}/contents/${path}`,env.GITHUB_TOKEN);if(!current.ok)return json({error:"Photo not found."},404,origin);const data=await current.json();const result=await githubRequest(`/repos/${REPO}/contents/${path}`,env.GITHUB_TOKEN,{method:"DELETE",body:JSON.stringify({message:`Remove nail photo ${filename}`,sha:data.sha})});if(!result.ok)return json({error:"GitHub could not delete the photo."},502,origin);const captions=await getCaptions(env);delete captions[filename];await saveCaptions(captions,env);return json({ok:true},200,origin,{"Cache-Control":"no-store"})}
async function getCaptions(env){const result=await githubRequest(`/repos/${REPO}/contents/${CAPTIONS_FILE}`,env.GITHUB_TOKEN);if(result.status===404)return{};if(!result.ok)throw new Error(`GitHub captions request failed: ${result.status}`);const data=await result.json();try{const binary=atob(data.content.replace(/\n/g,""));return JSON.parse(new TextDecoder().decode(Uint8Array.from(binary,c=>c.charCodeAt(0))))}catch{return{}}}
async function saveCaptions(captions,env){const current=await githubRequest(`/repos/${REPO}/contents/${CAPTIONS_FILE}`,env.GITHUB_TOKEN);const sha=current.ok?(await current.json()).sha:undefined;const content=toBase64Sync(new TextEncoder().encode(JSON.stringify(captions,null,2)+"\n"));const body={message:"Update nail photo captions",content};if(sha)body.sha=sha;const result=await githubRequest(`/repos/${REPO}/contents/${CAPTIONS_FILE}`,env.GITHUB_TOKEN,{method:"PUT",body:JSON.stringify(body)});if(!result.ok)throw new Error(`GitHub captions save failed: ${result.status}`)}
async function githubRequest(path,token,options={}){return fetch(`${GITHUB_API}${path}`,{...options,headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${token}`,"X-GitHub-Api-Version":"2026-03-10","User-Agent":"Autumn-Nails-Upload-Worker",...(options.headers||{})}})}
function makeFilename(original){const extension=original.toLowerCase().match(/\.(jpe?g|png|webp)$/)?.[1]||"jpg";const base=original.replace(/\.[^.]+$/," ").replace(/[^a-z0-9]+/gi,"-").replace(/^-+|-+$/g,"").slice(0,50)||"nail-set";const stamp=new Date().toISOString().replace(/[:.]/g,"-");return`${stamp}-${crypto.randomUUID().slice(0,8)}-${base}.${extension}`}
async function sign(value,secret){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64url(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value)))}
function safeEqual(a,b){if(a.length!==b.length)return false;let result=0;for(let i=0;i<a.length;i++)result|=a.charCodeAt(i)^b.charCodeAt(i);return result===0}
function b64url(value){const bytes=typeof value==="string"?new TextEncoder().encode(value):new Uint8Array(value);let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function fromB64url(value){const padded=value.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((value.length+3)%4);return new TextDecoder().decode(Uint8Array.from(atob(padded),c=>c.charCodeAt(0)))}
async function toBase64(buffer){return toBase64Sync(new Uint8Array(buffer))}
function toBase64Sync(bytes){let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}